name: Deploy Website to CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-modules-cache: 'npm'

      - name: Install and Build Dependencies
        run: |
          npm ci
          npm run build

      - name: Authenticate with AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Sync Production Files to S3 Bucket
        run: |
          aws s3 sync ./dist s3://${{ env.AWS_S3_BUCKET }} --delete

      - name: Invalidate Old CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
